stages:
  - deploy

deploy-job:
  stage: deploy
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - docker info
    - docker stop discord_bot || true
    - docker rm discord_bot || true
    - docker build --pull --network=host -t discord_music_bot .
    - echo MUSIC_BOT_TOKEN=$MUSIC_BOT_TOKEN
    - docker run -d --name discord_bot --restart unless-stopped -e MUSIC_BOT_TOKEN=$MUSIC_BOT_TOKEN discord_music_bot
  only:
    - main
