stages:
  - deploy

deploy-job:
  stage: deploy
  variables:
    DOCKER_HOST: unix:///var/run/docker.sock
  script:
    - docker stop discord_bot || true
    - docker rm discord_bot || true
    - docker build --pull --network=host -t discord_music_bot .
    - echo MUSIC_BOT_TOKEN=$MUSIC_BOT_TOKEN
    - docker run -d --name gitlab-runner --restart always -v /var/run/docker.sock:/var/run/docker.sock -v /etc/gitlab-runner:/etc/gitlab-runner gitlab/gitlab-runner:alpine
  only:
    - main